### ISSUE TITLE
[Feature Request] ControlNet-Reference Support for Video Generate

### ISSUE THREAD

**Issue by toyxyz** [s9roll7/animatediff-cli-prompt-travel#23] opened 2023-08-30 12:24 UTC
Currently ControlNet references are only available for upscale. Is it possible to add to the video generation as well? It would be very useful if possible! Thanks!

**Comment by Ratinod** [comment] 2023-08-31 20:14
There is also an IP-adapter and it also does this very well:
- https://github.com/ykk648/AnimateDiff/commit/cbcf29285adf39a3c82033c16ee064e521428eae )
- https://github.com/tencent-ailab/IP-Adapter
It is not known just how much more expensive it is in terms of computing power compared to CN references.
Ideally, I would like both.

**Comment by xnmt9** [comment] 2023-09-01 04:20
@Ratinod I've tried a few times to merge IPAdapter here but haven't been able to figure it out - hopefully someone better can take a stab at it

**Comment by s9roll7** [comment] 2023-09-02 14:21
cf6aab8

**Comment by xnmt9** [comment] 2023-09-02 14:36
@s9roll7 this is epic 🔥 excited to test it out 

quick q - is there a guess mode equivalent to the ref image controlnet?

**Comment by s9roll7** [comment] 2023-09-02 14:44
In the controlnet ref implementation of diffusers,
guess mode was not included

**Comment by JCBrouwer** [comment] 2023-09-02 15:20
Sweet, nice work @s9roll7 !

I gave implementing IP-adapter a try, see: https://github.com/s9roll7/animatediff-cli-prompt-travel/compare/main...JCBrouwer:animatediff-cli-prompt-travel:ip-adapter

Results aren't too good so far, but it does seem to be at least partially working:
![00_2792009891289740509_](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/15871226/b15e4d52-731e-48a2-b11f-1484e4b74ab8)
image prompt at 0:
<img src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/15871226/ea6336e9-5bf2-43a8-a752-ad769faf471f" width="256" height="256" />
image prompt at 16:
<img src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/15871226/df6cb37c-f85d-42f3-a494-897b1a33cc1b" width="256" height="256" />

**Comment by JCBrouwer** [comment] 2023-09-02 15:30
Here's the second (darker) image used with the controlnet_ref configuration from above:
> ```
>     "controlnet_ref": {
>         "enable": false,            # enable/disable (important)
>         "ref_image": "ref_image/ref_sample.png",     # path to reference image.
>         "attention_auto_machine_weight": 1.0,
>         "gn_auto_machine_weight": 1.0,
>         "style_fidelity": 0.5,                # control weight-like parameter(important)
>         "reference_attn": true,               # [attn=true , adain=false] means "reference_only"
>         "reference_adain": false,
>         "scale_pattern":[0.5]                 # Pattern for applying controlnet_ref to frames
>     }                                         # ex. [0.5] means [0.5,0.5,0.5,0.5,0.5 .... ]. All frames are affected by 50%
>                                               # ex. [1, 0] means [1,0,1,0,1,0,1,0,1,0,1 ....]. Only even frames are affected by 100%.
> ```


![00_5265660157068533039_](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/15871226/1290ef71-98a2-43e4-84ac-86c2f6d37cdd)

**Comment by s9roll7** [comment] 2023-09-03 06:58
082a2b7😅

**Comment by s9roll7** [comment] 2023-09-03 07:08
Is IP-adapter a technique that uses images instead of prompts?
It would be nice not to have to worry about prompt.

**Comment by xnmt9** [comment] 2023-09-03 07:20
@s9roll7 yep. Someone did a port to native Animatediff that works pretty well (though it's a little bit hacky): https://github.com/ykk648/AnimateDiff/tree/main/ip_adapter

**Comment by toyxyz** [comment] 2023-09-03 07:23
> 
I used ComfyUI animateDiff with Ip-adapter to get the following results. 

![AnimateDiff_00347_](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/e0e137f0-a519-4f5d-b646-b88af3981f8c)
Input image
![2c81907395d2be50feaeda79343b13d9](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/97a3448b-9314-48aa-98d9-cab5b171d1c0)


> Is IP-adapter a technique that uses images instead of prompts? It would be nice not to have to worry about prompt.

**Comment by s9roll7** [comment] 2023-09-03 07:35
> > 
> 
> I used ComfyUI animateDiff with Ip-adapter to get the following results.
> 
> ![AnimateDiff_00347_](https://user-images.githubusercontent.com/8006000/265248114-e0e137f0-a519-4f5d-b646-b88af3981f8c.gif) Input image ![2c81907395d2be50feaeda79343b13d9](https://user-images.githubusercontent.com/8006000/265248119-97a3448b-9314-48aa-98d9-cab5b171d1c0.jpg)
> 
> > Is IP-adapter a technique that uses images instead of prompts? It would be nice not to have to worry about prompt.

Is this one same input image applied to all frames?

**Comment by toyxyz** [comment] 2023-09-03 07:38
> > > 
> > 
> > 
> > I used ComfyUI animateDiff with Ip-adapter to get the following results.
> 
> > > Is IP-adapter a technique that uses images instead of prompts? It would be nice not to have to worry about prompt.
> 
> Is this one same input image applied to all frames?

Yes. I put a single image into the Ip adapter, used the Wd 14 tagger, and typed the prompts together. The motion used an openpose.

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/1eb3ea7f-2100-423c-8560-52a6d721eb8b)


Using just the prompts without an IP adapter will generate a video like the one below

![AnimateDiff_00200_](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/f3dd276a-9f2a-446f-948e-366e1b16d918)

**Comment by s9roll7** [comment] 2023-09-03 07:41
Thank you. I understood.
It's certainly something that works well with animatediff.

**Comment by s9roll7** [comment] 2023-09-03 16:45
> I gave implementing IP-adapter a try, see: [main...JCBrouwer:animatediff-cli-prompt-travel:ip-adapter](https://github.com/s9roll7/animatediff-cli-prompt-travel/compare/main...JCBrouwer:animatediff-cli-prompt-travel:ip-adapter)

I used this implementation as a reference for the merge and it worked for the most part. Thank you

**Comment by s9roll7** [comment] 2023-09-04 12:47
ba4ce65
```
  "ip_adapter_map": {       # config for ip-adapter
      # enable/disable (important)
      "enable": true,
      # Specify input image directory relative to /animatediff-cli/data (important! No need to specify frames in the config file. The effect on generation is exactly the same logic as the placement of the prompt)
      "input_image_dir": "ip_adapter_image/test",
      # save input image or not
      "save_input_image": true,
      # Ratio of image prompt vs text prompt (important). Even if you want to emphasize only the image prompt in 1.0, do not leave prompt/neg prompt empty, but specify a general text such as "best quality".
      "scale": 0.5,
      # IP-Adapter or IP-Adapter Plus (important) It would be a completely different outcome. Not always PLUS a superior result.
      "is_plus": true
  },
```

**Comment by toyxyz** [comment] 2023-09-04 14:48
I tried to use a controlnet ref and got the following error

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/0b89a9bd-76c7-4d53-81f3-b7fcb302882f)


╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\cli.py:368 in generate              │
│                                                                                                  │
│   365 │   │   │   │   if int(k) < length:                                                        │
│   366 │   │   │   │   │   prompt_map[int(k)]=model_config.prompt_map[k]                          │
│   367 │   │   │                                                                                  │
│ ❱ 368 │   │   │   output = run_inference(                                                        │
│   369 │   │   │   │   pipeline=pipeline,                                                         │
│   370 │   │   │   │   prompt="this is dummy string",                                             │
│   371 │   │   │   │   n_prompt=n_prompt,                                                         │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\generate.py:593 in run_inference    │
│                                                                                                  │
│   590 │                                                                                          │
│   591 │   seed_everything(seed)                                                                  │
│   592 │                                                                                          │
│ ❱ 593 │   pipeline_output = pipeline(                                                            │
│   594 │   │   prompt=prompt,                                                                     │
│   595 │   │   negative_prompt=n_prompt,                                                          │
│   596 │   │   num_inference_steps=steps,                                                         │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\utils\_contextlib.py:1 │
│ 15 in decorate_context                                                                           │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\pipelines\animation.py:2308 in      │
│ __call__                                                                                         │
│                                                                                                  │
│   2305 │   │   │   │   │   # predict the noise residual                                          │
│   2306 │   │   │   │   │                                                                         │
│   2307 │   │   │   │   │   stopwatch_record("normal unet start")                                 │
│ ❱ 2308 │   │   │   │   │   pred = self.unet(                                                     │
│   2309 │   │   │   │   │   │   latent_model_input.to(self.unet.device, self.unet.dtype),         │
│   2310 │   │   │   │   │   │   t,                                                                │
│   2311 │   │   │   │   │   │   encoder_hidden_states=cur_prompt,                                 │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 501 in _call_impl                                                                                │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\models\unet.py:421 in forward       │
│                                                                                                  │
│   418 │   │   down_block_res_samples = (sample,)                                                 │
│   419 │   │   for downsample_block in self.down_blocks:                                          │
│   420 │   │   │   if hasattr(downsample_block, "has_cross_attention") and downsample_block.has   │
│ ❱ 421 │   │   │   │   sample, res_samples = downsample_block(                                    │
│   422 │   │   │   │   │   hidden_states=sample,                                                  │
│   423 │   │   │   │   │   temb=emb,                                                              │
│   424 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 501 in _call_impl                                                                                │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\models\unet_blocks.py:419 in        │
│ forward                                                                                          │
│                                                                                                  │
│   416 │   │   │                                                                                  │
│   417 │   │   │   else:                                                                          │
│   418 │   │   │   │   hidden_states = resnet(hidden_states, temb)                                │
│ ❱ 419 │   │   │   │   hidden_states = attn(                                                      │
│   420 │   │   │   │   │   hidden_states,                                                         │
│   421 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│   422 │   │   │   │   │   cross_attention_kwargs=cross_attention_kwargs,                         │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 501 in _call_impl                                                                                │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\models\attention.py:145 in forward  │
│                                                                                                  │
│   142 │   │                                                                                      │
│   143 │   │   # 2. Blocks                                                                        │
│   144 │   │   for block in self.transformer_blocks:                                              │
│ ❱ 145 │   │   │   hidden_states = block(                                                         │
│   146 │   │   │   │   hidden_states,                                                             │
│   147 │   │   │   │   attention_mask=attention_mask,                                             │
│   148 │   │   │   │   encoder_hidden_states=encoder_hidden_states,                               │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 501 in _call_impl                                                                                │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\pipelines\animation.py:1242 in      │
│ hacked_basic_transformer_inner_forward                                                           │
│                                                                                                  │
│   1239 │   │   │   │   │   if attention_auto_machine_weight > self.attn_weight:                  │
│   1240 │   │   │   │   │   │   attn_output_uc = self.attn1(                                      │
│   1241 │   │   │   │   │   │   │   norm_hidden_states,                                           │
│ ❱ 1242 │   │   │   │   │   │   │   encoder_hidden_states=torch.cat([norm_hidden_states] + self.  │
│   1243 │   │   │   │   │   │   │   # attention_mask=attention_mask,                              │
│   1244 │   │   │   │   │   │   │   **cross_attention_kwargs,                                     │
│   1245 │   │   │   │   │   │   )                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 32 but got size 48 for tensor number 1 inthe list.

**Comment by s9roll7** [comment] 2023-09-04 23:12
@toyxyz 
can you upload your ref.png?

**Comment by toyxyz** [comment] 2023-09-05 03:16
> @toyxyz can you upload your ref.png?
Here!

![ref](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/73c45e27-158a-41d1-b41b-7a4981a7d13b)

**Comment by s9roll7** [comment] 2023-09-05 03:42
![00_3192962043_masterpiece_best-quality_russian-girl_woman_smile_dramatic-lighting](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/118420657/c0c4b09e-8614-41a4-b62d-032dbbf01d71)
It did not reproduce.
I think the image you pasted here is changing the format on its own.
Is the original image 48-bit color channel?

**Comment by toyxyz** [comment] 2023-09-05 04:01
The original image is 24 bit

**Comment by s9roll7** [comment] 2023-09-05 05:19
> The original image is 24 bit
hmm...
I prepared a 48bit png and tried it but could not reproduce it.
Apparently not.
I would like to reproduce it anyway.
Can you upload the config file?
And let me know what command you used and your OS.

**Comment by toyxyz** [comment] 2023-09-05 05:35
> > The original image is 24 bit
> 
> hmm... I prepared a 48bit png and tried it but could not reproduce it. Apparently not. I would like to reproduce it anyway. Can you upload the config file? And let me know what command you used and your OS.

Here https://pastebin.com/i9wcFXnx

**Comment by s9roll7** [comment] 2023-09-05 06:25
![00_619189172829500_masterpiece_best-quality_1girl_solo_full-body_standing](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/118420657/867bd7e5-27c4-4134-a8b9-88ea48edff41)

Illustration_Counterfeit-V3.0_fp32.safetensors
is not found, so
Counterfeit-V3.0_fp32.safetensors
I used
I tried with controlnet_ref set to true, but it didn't give me any errors.

**Comment by s9roll7** [comment] 2023-09-05 09:31
I've implemented it, so I'm closing it for now.
If you still have errors, please open a new issue.

**Closed by s9roll7** 2023-09-05 09:31 UTC
